---
title: "Reproducible Research: Peer Assessment 1"
author: Pauleen Teoh Gei San
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data

Code for reading in the dataset and/or processing the data

```{R prepdata, echo = TRUE}

zip_file <- "Activity.zip"

# Checking if archieve already exists.
if(!file.exists(zip_file)){
    file_url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
    download.file(file_url, zip_file, method="curl")
} 

# Checking if folder exists
if(!file.exists("./")) { 
    unzip(zip_file) 
}

# read data from activity.csv into activity_df data frame
activity_df <- read.csv("activity.csv")  
```

## What is mean total number of steps taken per day?

For this part of the assignment, you can ignore the missing values in the dataset.

1. Calculate the total number of steps taken per day

```{R totalstepsperday, echo = TRUE}
tot_steps_a_day <- tapply(activity_df$steps, activity_df$date, sum)
tot_steps_a_day
```

2. If you do not understand the difference between a histogram and a barplot, research the difference between them. Make a histogram of the total number of steps taken each day

```{R histtotnumofstepsperday0, echo = TRUE}
hist(tot_steps_a_day, breaks = length(tot_steps_a_day), main = "Total number of steps taken each day", xlab = "Total steps")
```

3. Calculate and report the mean and median of the total number of steps taken per day

```{R meanmedianreport, echo = TRUE}
calc <- summary(tot_steps_a_day)

print(paste("Mean:", round(calc["Mean"],0)))
print(paste("Median:", round(calc["Median"],0)))
```

## What is the average daily activity pattern?

1. Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

``` {R timeseriesplot, echo = TRUE}
mean_steps_a_day <- tapply(activity_df$steps, activity_df$interval, mean, na.rm = TRUE)

plot(names(mean_steps_a_day), mean_steps_a_day, xlab = "5-minute interval", ylab = "Average number of steps", type = "l")
```

2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

``` {R maxnumofsteps, echo = TRUE}
maxnum <- which.max(mean_steps_a_day)
print(paste("5-minute interval contaians maximum number of steps:", names(maxnum)))
```

## Imputing missing values

Note that there are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data.

1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

```{R totalmissingvalues, echo = TRUE}
missing_val <- is.na(activity_df$steps)
tot_missing <- length(missing_val[missing_val==TRUE])
print(paste("Total number of rows with NAs:", tot_missing))
```

2. Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 
5-minute interval, etc.

```{R fillmissingvalues, echo = TRUE}
mean_steps_df <- data.frame(cbind(mean_steps_a_day))
colnames(mean_steps_df) <- "mean.steps"
head(mean_steps_df)
```

3. Create a new dataset that is equal to the original dataset but with the missing data filled in.

```{R newdataset, echo = TRUE}
new_dataset <- activity_df

new_dataset$steps <- ifelse(is.na(new_dataset$steps), mean_steps_df$mean.steps, new_dataset$steps)
head(new_dataset)
```

4. Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

```{R histtotnumofstepsperday1, echo = TRUE}
tot_steps_a_day <- tapply(new_dataset$steps, new_dataset$date, sum)
hist(tot_steps_a_day, breaks = length(tot_steps_a_day), main = "Total number of steps taken each day", xlab = "Total steps")

calc <- summary(tot_steps_a_day)

print(paste("Mean:", round(calc["Mean"],0)))
print(paste("Median:", round(calc["Median"],0)))
```

After imputing missing data, the frequency of total 10,000 steps is higher compare to the first part of the assignment. However the Mean and Median are almost the same.

## Are there differences in activity patterns between weekdays and weekends?

For this part the weekdays() function may be of some help here. Use the dataset with the filled-in missing values for this part.

1. Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.

```{R weekdaysfactorvariable, echo = TRUE}
new_dataset$date <- strptime(new_dataset$date, "%Y-%m-%d")
new_dataset$factor <- ifelse((weekdays(new_dataset$date) %in% c("Monday", "Tuesday","Wednesday","Thursday","Friday")), "Weekday","Weekend")

head(new_dataset)
```

2. Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.

```{R timeseriesplotbyfactor, echo = TRUE}
library(ggplot2)
library(dplyr)

by_interval_factor <- new_dataset %>% group_by(interval, factor) %>% summarise(avg_steps = mean(steps, na.rm = TRUE))

g <- ggplot(data = by_interval_factor, mapping = aes(x = interval, 
  y = avg_steps)) + geom_line() + facet_grid(factor ~ .) +
  scale_x_continuous("5-minute interval",                             breaks = seq(min(by_interval_factor$interval),
  max(by_interval_factor$interval), 150)) + 
  scale_y_continuous("Average number of steps") + 
  ggtitle("Average number of steps taken by 5-minute interval")
g
```

The average steps on Weekday at interval 825 is higher than weekend, however subsequently the average steps on weekend increase at interval between 1200 and 1650. More activities are happening within this interval compare to weekday.
